#!/bin/bash
scriptdir="."
cp -v $scriptdir/Physics-model-templates/00-to-51.phyA $scriptdir/Eternal-Physics.phyA 
cp -v $scriptdir/Physics-model-templates/00-to-51.phyA $scriptdir/Eternal-Maps-merge-folder/00-The-Far-Side-Of-Nowhere/The-Far-Side-Of-Nowhere.phyA 
cp -v $scriptdir/Physics-model-templates/00-to-51.phyA $scriptdir/Eternal-Maps-merge-folder/01-Deja-Vu-All-Over-Again/Deja-Vu-All-Over-Again.phyA 
cp -v $scriptdir/Physics-model-templates/00-to-51.phyA $scriptdir/Eternal-Maps-merge-folder/02-Septococcal-Pfhoryngitis/Septococcal-Pfhoryngitis.phyA 
cp -v $scriptdir/Physics-model-templates/00-to-51.phyA $scriptdir/Eternal-Maps-merge-folder/03-Dysmentria/Dysmentria.phyA 
cp -v $scriptdir/Physics-model-templates/00-to-51.phyA $scriptdir/Eternal-Maps-merge-folder/04-Sakhmet-Rising/Sakhmet-Rising.phyA 
cp -v $scriptdir/Physics-model-templates/00-to-51.phyA $scriptdir/Eternal-Maps-merge-folder/05-Unwired/Unwired.phyA 
cp -v $scriptdir/Physics-model-templates/00-to-51.phyA $scriptdir/Eternal-Maps-merge-folder/06-Roots-And-Radicals/Roots-And-Radicals.phyA 
cp -v $scriptdir/Physics-model-templates/00-to-51.phyA $scriptdir/Eternal-Maps-merge-folder/07-The-Tangent-Universe/The-Tangent-Universe.phyA 
cp -v $scriptdir/Physics-model-templates/00-to-51.phyA $scriptdir/Eternal-Maps-merge-folder/08-Core-Done-Blew/Core-Done-Blew.phyA 
cp -v $scriptdir/Physics-model-templates/00-to-51.phyA $scriptdir/Eternal-Maps-merge-folder/09-Heart-of-Fusion/Heart-of-Fusion.phyA 
cp -v $scriptdir/Physics-model-templates/00-to-51.phyA $scriptdir/Eternal-Maps-merge-folder/10-To-Sleep\,-Perchance-to-Dream/To-Sleep\,-Perchance-to-Dream.phyA 
cp -v $scriptdir/Physics-model-templates/00-to-51.phyA $scriptdir/Eternal-Maps-merge-folder/11-Hysterical-Womb/Hysterical-Womb.phyA 
cp -v $scriptdir/Physics-model-templates/12-to-16.phyA $scriptdir/Eternal-Maps-merge-folder/12-A-Friend-In-Need/A-Friend-In-Need.phyA 
cp -v $scriptdir/Physics-model-templates/12-to-16.phyA $scriptdir/Eternal-Maps-merge-folder/13-Unlucky-Pfhor-Some/Unlucky-Pfhor-Some.phyA 
cp -v $scriptdir/Physics-model-templates/12-to-16.phyA $scriptdir/Eternal-Maps-merge-folder/14-Unpfhorseen/Unpfhorseen.phyA 
cp -v $scriptdir/Physics-model-templates/12-to-16.phyA $scriptdir/Eternal-Maps-merge-folder/15-Killing-the-Giants-as-They-Sleep/Killing-the-Giants-as-They-Sleep.phyA 
cp -v $scriptdir/Physics-model-templates/12-to-16.phyA $scriptdir/Eternal-Maps-merge-folder/16-Pissing-on-the-Corporation/Pissing-on-the-Corporation.phyA 
cp -v $scriptdir/Physics-model-templates/00-to-51.phyA $scriptdir/Eternal-Maps-merge-folder/17-The-Living-Receiver/The-Living-Receiver.phyA 
cp -v $scriptdir/Physics-model-templates/00-to-51.phyA $scriptdir/Eternal-Maps-merge-folder/18-My-Kingdom-Pfhor-A-Horse/My-Kingdom-Pfhor-A-Horse.phyA 
cp -v $scriptdir/Physics-model-templates/00-to-51.phyA $scriptdir/Eternal-Maps-merge-folder/19-Burning-Down-The-Corporation/Burning-Down-The-Corporation.phyA 
cp -v $scriptdir/Physics-model-templates/00-to-51.phyA $scriptdir/Eternal-Maps-merge-folder/20-The-World-Is-Hollow/The-World-Is-Hollow.phyA 
cp -v $scriptdir/Physics-model-templates/21-to-23.phyA $scriptdir/Eternal-Maps-merge-folder/21-S\'pht\'ia/S\'pht\'ia.phyA 
cp -v $scriptdir/Physics-model-templates/21-to-23.phyA $scriptdir/Eternal-Maps-merge-folder/22-Let-Sleeping-Gods-Die/Let-Sleeping-Gods-Die.phyA 
cp -v $scriptdir/Physics-model-templates/21-to-23.phyA $scriptdir/Eternal-Maps-merge-folder/23-She-Is-The-Dark-One/She-Is-The-Dark-One.phyA 
cp -v $scriptdir/Physics-model-templates/24-to-26.phyA $scriptdir/Eternal-Maps-merge-folder/24-S\'pht-Happens/S\'pht-Happens.phyA 
cp -v $scriptdir/Physics-model-templates/24-to-26.phyA $scriptdir/Eternal-Maps-merge-folder/25-Eat-S\'pht-and-Die/25-Eat-S\'pht-and-Die.phyA 
cp -v $scriptdir/Physics-model-templates/24-to-26.phyA $scriptdir/Eternal-Maps-merge-folder/26-Second-to-Last-of-the-Mohicans/Second-to-Last-of-the-Mohicans.phyA 
cp -v $scriptdir/Physics-model-templates/27-to-29.phyA $scriptdir/Eternal-Maps-merge-folder/27-The-Manipulated-Dead/The-Manipulated-Dead.phyA 
cp -v $scriptdir/Physics-model-templates/27-to-29.phyA $scriptdir/Eternal-Maps-merge-folder/28-Third-Rock-from-Lh\'owon/Third-Rock-from-Lh\'owon.phyA 
cp -v $scriptdir/Physics-model-templates/27-to-29.phyA $scriptdir/Eternal-Maps-merge-folder/29-Flight-Of-Icarus/Flight-Of-Icarus.phyA 
cp -v $scriptdir/Physics-model-templates/00-to-51.phyA $scriptdir/Eternal-Maps-merge-folder/30-The-Land-In-The-Sky/The-Land-In-The-Sky.phyA 
cp -v $scriptdir/Physics-model-templates/31-to-33.phyA $scriptdir/Eternal-Maps-merge-folder/31-Pfhor-Faar-Lamm/Pfhor-Faar-Lamm.phyA 
cp -v $scriptdir/Physics-model-templates/31-to-33.phyA $scriptdir/Eternal-Maps-merge-folder/32-The-Incredible-Hulk/The-Incredible-Hulk.phyA 
cp -v $scriptdir/Physics-model-templates/31-to-33.phyA $scriptdir/Eternal-Maps-merge-folder/33-Babylon-X/Babylon-X.phyA 
cp -v $scriptdir/Physics-model-templates/34-to-39.phyA $scriptdir/Eternal-Maps-merge-folder/34-Dread-Not/Dread-Not.phyA 
cp -v $scriptdir/Physics-model-templates/34-to-39.phyA $scriptdir/Eternal-Maps-merge-folder/35-Bug-Eyed-In-Space/Bug-Eyed-In-Space.phyA
cp -v $scriptdir/Physics-model-templates/36.phyA $scriptdir/Eternal-Maps-merge-folder/36-Run\,-Coward\!/Run\,-Coward\!.phyA 
cp -v $scriptdir/Physics-model-templates/34-to-39.phyA $scriptdir/Eternal-Maps-merge-folder/37-The-Ensurance-Trap/The-Ensurance-Trap.phyA
cp -v $scriptdir/Physics-model-templates/34-to-39.phyA $scriptdir/Eternal-Maps-merge-folder/38-Once-More-Unto-The-Breach..$scriptdir/Once-More-Unto-The-Breach....phyA 
cp -v $scriptdir/Physics-model-templates/34-to-39.phyA $scriptdir/Eternal-Maps-merge-folder/39-Genie-In-A-Bottle/Genie-In-A-Bottle.phyA 
cp -v $scriptdir/Physics-model-templates/00-to-51.phyA $scriptdir/Eternal-Maps-merge-folder/40-Floating-In-The-Void/Floating-In-The-Void.phyA 
cp -v $scriptdir/Physics-model-templates/00-to-51.phyA $scriptdir/Eternal-Maps-merge-folder/41-Echoes-of-Eden/Echoes-of-Eden.phyA 
cp -v $scriptdir/Physics-model-templates/00-to-51.phyA $scriptdir/Eternal-Maps-merge-folder/42-The-Dead-Live-In-The-Catacombs/The-Dead-Live-In-The-Catacombs.phyA 
cp -v $scriptdir/Physics-model-templates/00-to-51.phyA $scriptdir/Eternal-Maps-merge-folder/43-These-Caves-Can’t-Be-a-Natural-Formation/These-Caves-Can’t-Be-a-Natural-Formation.phyA 
cp -v $scriptdir/Physics-model-templates/00-to-51.phyA $scriptdir/Eternal-Maps-merge-folder/44-Deep-Into-The-Grotto/Deep-Into-The-Grotto.phyA 
cp -v $scriptdir/Physics-model-templates/00-to-51.phyA $scriptdir/Eternal-Maps-merge-folder/45-Frog-Blast-The-Vent-Core/Frog-Blast-The-Vent-Core.phyA 
cp -v $scriptdir/Physics-model-templates/00-to-51.phyA $scriptdir/Eternal-Maps-merge-folder/46-I\'ve-Got-A-Bad-Feeling-About-This/I\'ve-Got-A-Bad-Feeling-About-This.phyA 
cp -v $scriptdir/Physics-model-templates/00-to-51.phyA $scriptdir/Eternal-Maps-merge-folder/47-The-Philosophy-Of-Time-Travel/The-Philosophy-Of-Time-Travel.phyA 
cp -v $scriptdir/Physics-model-templates/00-to-51.phyA $scriptdir/Eternal-Maps-merge-folder/48-This-Message-Will-Self-Destruct/This-Message-Will-Self-Destruct.phyA 
cp -v $scriptdir/Physics-model-templates/00-to-51.phyA $scriptdir/Eternal-Maps-merge-folder/49-We-Met-Once-in-the-Garden/We-Met-Once-in-the-Garden.phyA 
cp -v $scriptdir/Physics-model-templates/00-to-51.phyA $scriptdir/Eternal-Maps-merge-folder/50-Where-Giants-Have-Fallen/Where-Giants-Have-Fallen.phyA 
cp -v $scriptdir/Physics-model-templates/00-to-51.phyA $scriptdir/Eternal-Maps-merge-folder/51-The-Near-Side-Of-Everywhere/The-Near-Side-Of-Everywhere.phyA 
